### ISSUE TITLE
navrh implementacie

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#13]
- [x] UML component diagram #36 
- [x] UML class diagram #37
- [x] UML sequence diagram #38
- [x] interfejsy #35 
- [x] technologie #39 
- [x] databaza #16
