### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by ZuzanaMa** [TIS2021-FMFI/dekk#19]
<b>GUI -  Laravel </b>                                                                  
- [x] database migration for db scheme #20  @ZuzanaMa                                   
- [x] "generate skript" - db seeder  #21     @ZuzanaMa                                       
- [x] section with all datasets listed #22
- [x] search bar #23
- [x] section with selected datasets and parametres #24 - podmienene #22
- [x] download button - map #40 @Achinys-out 
- [x] download button - graph #41  @sinthoras50 
- [x] graph visualisation #25 @sinthoras50 
- [x] correlation calculation #26 @ZuzanaMa 
- [x] coloring the map #27 @sinthoras50 
- [x] year bar #28 podmienene #24
- [x] prerobit frontend #53 @Achinys-out 
- [x] finalny seeder pre databazu #29 @ZuzanaMa 

<b>Import scripts</b>
- [x] import data from api in json format (automatic) #30 @rikimis 
- [x] import data manually from .csv #31 @rikimis
